import { renderDrawer, renderModal } from './modes'
import type { KYIMode, KYIOptions, KYIScope, KYIWidget } from './types'

/**
 * Create a KYI widget instance
 *
 * @param mode - Display mode: 'drawer'
 * @param scope - Widget scope: 'kyi', 'asset-list', 'wallet', or 'wallet-list'
 * @param accessToken - Access token generated by generateToken()
 * @param options - Optional configuration
 * @returns Widget instance with destroy method
 *
 * @example
 * ```typescript
 * const widget = kyi('drawer', 'kyi', accessToken, {
 *   onClose: () => console.log('Drawer closed'),
 * });
 *
 * // Clean up when done
 * widget.destroy();
 * ```
 */
export function kyi(
  mode: KYIMode,
  scope: KYIScope,
  accessToken: string,
  options: KYIOptions = {}
): KYIWidget {
  if (!accessToken) {
    throw new Error('Access token is required')
  }

  switch (mode) {
    case 'modal':
      return renderModal(scope, accessToken, options)
    case 'drawer':
      return renderDrawer(scope, accessToken, options)
    default:
      throw new Error(`Invalid mode: ${mode}. Expected 'modal' or 'drawer'.`)
  }
}
